import Link from 'next/link';
import type { Metadata } from 'next';
import { LandingNav } from '@/components/LandingNav';
import { GALLERY, galleryPack } from '@/lib/gallery';
import styles from '../landing.module.css';
import gallery from './gallery.module.css';

/**
 * The template gallery index (§3 — "a public gallery of AGENTS.md rule-packs
 * and knowledge scaffolds per stack, each one a landing page").
 *
 * Statically generated: this is the acquisition surface, so it has to be a
 * page a crawler can read, not an app shell that fetches.
 */

export const metadata: Metadata = {
  title: 'specd — AGENTS.md templates and knowledge scaffolds, per stack',
  description:
    'The exact AGENTS.md and knowledge/ scaffold specd generates for NestJS, Next.js, Django, FastAPI, Go, Rust, Rails and Terraform repositories. Generated by the product, not written for the page.',
};

export default function TemplatesIndex() {
  const packs = GALLERY.map((entry) => galleryPack(entry));

  return (
    <main className={styles.page}>
      <LandingNav />
      <section className={styles.subhead}>
        <div className={styles.subin}>
          <Link href="/" className={styles.back}>
            ← BACK TO SITE
          </Link>
          <span className="tag">TEMPLATES</span>
          <h1 className={styles.subh1}>What specd writes into your repo</h1>
          <p className={styles.lede}>
            Every project starts with the same two files — <code>AGENTS.md</code>, the working
            agreements an agent must follow, and a <code>knowledge/</code> base it must read before
            writing anything. specd detects your stack and writes both, as a pull request you
            review like any other.
          </p>
          <p className={styles.lede}>
            Each page below is generated by the product itself, from a repository of that shape.
            Nothing here was written for the website.
          </p>

          <div className={gallery.grid}>
            {packs.map(({ entry, stack, summary }) => (
              <Link key={entry.slug} href={`/templates/${entry.slug}`} className={gallery.card}>
                <h2>{entry.title}</h2>
                <p>{entry.blurb}</p>
                <span className={gallery.detected}>{summary}</span>
                <code className={gallery.verify}>{stack.verifyCommand}</code>
              </Link>
            ))}
          </div>

          <span className="tag">WHY THESE ARE REAL</span>
          <p className={styles.lede}>
            Generated documentation is only worth reading if it is honest about what it knows.
            Every draft specd writes carries a <code>DRAFT</code> banner, and any claim the scan
            could not ground in your code is marked <code>UNVERIFIED</code> rather than asserted.
            The pull request says so too. You are reviewing a first draft, not adopting a fact.
          </p>
        </div>
      </section>
    </main>
  );
}
