import { type DetectedStack, describeStack } from './stack.js';

/**
 * AGENTS.md — the seven lines the whole product exists to make true (§7).
 * Rules 1–4 are the ePD operating model verbatim: knowledge-first,
 * docs-ride-the-PR, as-built specs. Everything specd does — the wizard that
 * installs this file, the gate that enforces rule 5, the webhook that verifies
 * rule 7 — exists to keep them honest.
 *
 * D6: emit both files. AGENTS.md is canonical (open standard, read by most
 * agents); CLAUDE.md is a one-line importer, so editing either keeps them in
 * sync by construction.
 */
export function renderAgentsMd(input: {
  repoName: string;
  stack: DetectedStack;
  isPrimary: boolean;
  projectName: string;
  /** Docs the scaffold actually emitted, so the map never points at a missing file. */
  docs?: string[];
}): string {
  const { repoName, stack, isPrimary, projectName, docs } = input;
  const stackLine = describeStack(stack) || 'not detected — please fill in';
  const verify = stack.verifyCommand ?? 'not detected — please fill in';

  const MAP: [string, string][] = [
    ['knowledge/product.md', 'what this system is for — read before writing requirements'],
    ['knowledge/architecture.md', 'boundaries and flows — read before crossing a module'],
    ['knowledge/conventions.md', 'commands, style, what a reviewer rejects'],
    ['knowledge/testing.md', 'what must have a test before a task is done'],
    ['knowledge/data-model.md', 'entities and the rules that outlive the code'],
    ['knowledge/integrations.md', 'everything outside this repo it depends on'],
    ['knowledge/glossary.md', 'the domain words, defined once'],
    ['knowledge/open-questions.md', 'what nobody has answered yet — ask, do not guess'],
  ];

  const mapLines = MAP.filter(([path]) => !docs || docs.includes(path))
    .map(([path, why]) => `- ${path} — ${why}`)
    .join('\n');

  return `# Working agreements for AI agents (generated by specd, v1 — edit freely)

## Knowledge first — no exceptions
1. Before implementing ANYTHING, read knowledge/README.md and the docs it
   maps to your task. Do not re-derive what is already written down.
2. Ground design choices in knowledge/ and cite the file you relied on
   in the PR description (e.g. "per knowledge/architecture.md#auth").
3. Update knowledge/ IN THE SAME PR as the code it describes.
   Docs ride the change; they never trail it.
4. knowledge/specs/ is a historical record (as-built). Never rewrite old
   specs; append a "Deviations" section if reality diverged.

## Spec-driven workflow
5. Work items arrive as approved specs (Requirements / Design / Tasks)
   from specd — fetch with: specd spec pull <id>
6. Implement tasks in order; one task ≤ one PR; reference the spec id
   in every branch (spec/<id>-<slug>) and PR title.
7. The final task of every spec: commit the as-built spec to
   knowledge/specs/<id>-<slug>.md in ${isPrimary ? 'this repo' : `the primary repo of ${projectName}`}'s PR.

## When the knowledge base does not answer you
8. Do not invent the answer. Check knowledge/open-questions.md; if it is
   listed there, say so in the PR or spec and ask a human. An UNVERIFIED
   marker is a question, never a licence to fill it in from guesswork.
9. If you learn the answer while implementing, write it into the doc it
   belongs in and delete the open question — in the same PR (rule 3).

## Ask the knowledge base, do not re-derive it
10. Where specd's knowledge tools are available, query them before reading
    the tree: they answer with the passage AND the string to cite it by,
    already checked. Grepping gets you the text and none of the evidence.

## The map
${mapLines}

## This repo
- Name: ${repoName}${isPrimary ? '  (primary — cross-repo specs land here)' : ''}
- Stack: ${stackLine}          [detected]
- Verify before PR: ${verify}           [detected]
- Spec shape: knowledge/specs/TEMPLATE.md            [generated]

## Wiring the knowledge tools (rule 10)
Point any MCP-capable editor at specd. It serves this project's knowledge
base and its approved specs, and it is read-only — approval stays a
signed-in human in the app.

    { "mcpServers": { "specd": { "command": "specd", "args": ["mcp", "serve"] } } }

Needs the specd CLI on your PATH and \`specd login\` once per machine.
Tools: search_knowledge · get_doc · verify_citation · knowledge_health ·
spec_status · spec_pull · list_specs
`;
}

export function renderClaudeMd(): string {
  return `# CLAUDE.md

@AGENTS.md

<!--
  specd emits both files by design (D6): AGENTS.md is canonical and read by
  most agents; this file is a thin pointer so Claude Code picks up the same
  rules natively. Edit AGENTS.md — this file needs no maintenance.
-->
`;
}
