import { type DetectedStack, describeStack } from './stack.js';

/**
 * AGENTS.md — the seven lines the whole product exists to make true (§7).
 * Rules 1–4 are the ePD operating model verbatim: knowledge-first,
 * docs-ride-the-PR, as-built specs. Everything specd does — the wizard that
 * installs this file, the gate that enforces rule 5, the webhook that verifies
 * rule 7 — exists to keep them honest.
 *
 * D6: emit both files. AGENTS.md is canonical (open standard, read by most
 * agents); CLAUDE.md is a one-line importer, so editing either keeps them in
 * sync by construction.
 */
export function renderAgentsMd(input: {
  repoName: string;
  stack: DetectedStack;
  isPrimary: boolean;
  projectName: string;
  /** Docs the scaffold actually emitted, so the map never points at a missing file. */
  docs?: string[];
}): string {
  const { repoName, stack, isPrimary, projectName, docs } = input;
  const stackLine = describeStack(stack) || 'not detected — please fill in';
  const verify = stack.verifyCommand ?? 'not detected — please fill in';

  const MAP: [string, string][] = [
    ['knowledge/product.md', 'what this system is for — read before writing requirements'],
    ['knowledge/architecture.md', 'boundaries and flows — read before crossing a module'],
    ['knowledge/conventions.md', 'commands, style, what a reviewer rejects'],
    ['knowledge/testing.md', 'what must have a test before a task is done'],
    ['knowledge/data-model.md', 'entities and the rules that outlive the code'],
    ['knowledge/integrations.md', 'everything outside this repo it depends on'],
    ['knowledge/glossary.md', 'the domain words, defined once'],
    ['knowledge/open-questions.md', 'what nobody has answered yet — ask, do not guess'],
  ];

  const mapLines = MAP.filter(([path]) => !docs || docs.includes(path))
    .map(([path, why]) => `- ${path} — ${why}`)
    .join('\n');

  return `# Working agreements for AI agents (generated by specd, v1 — edit freely)

## Knowledge first — no exceptions
1. Before implementing ANYTHING, read knowledge/README.md and the docs it
   maps to your task. Do not re-derive what is already written down.
2. Ground design choices in knowledge/ and cite the file you relied on
   in the PR description (e.g. "per knowledge/architecture.md#auth").
3. Update knowledge/ IN THE SAME PR as the code it describes.
   Docs ride the change; they never trail it.
4. knowledge/specs/ is a historical record (as-built). Never rewrite old
   specs; append a "Deviations" section if reality diverged.

## Spec-driven workflow
5. Work items arrive as approved specs (Requirements / Design / Tasks)
   from specd — fetch with: specd spec pull <id>
6. Implement tasks in order; one task ≤ one PR. Branch as
   spec/<ID>-<slug> and title the PR "[<ID>] - <Title>" — the id is
   spelled the way the board spells it, in both.
7. The final task of every spec: commit the as-built spec to
   knowledge/specs/<id>-<slug>.md in ${isPrimary ? 'this repo' : `the primary repo of ${projectName}`}'s PR.

## When the knowledge base does not answer you
8. Do not invent the answer. Check knowledge/open-questions.md; if it is
   listed there, say so in the PR or spec and ask a human. An UNVERIFIED
   marker is a question, never a licence to fill it in from guesswork.
9. If you learn the answer while implementing, write it into the doc it
   belongs in and delete the open question — in the same PR (rule 3).

## Ask the knowledge base, do not re-derive it
10. Where specd's knowledge tools are available, query them before reading
    the tree: they answer with the passage AND the string to cite it by,
    already checked. Grepping gets you the text and none of the evidence.

## The map
${mapLines}

## This repo
- Name: ${repoName}${isPrimary ? '  (primary — cross-repo specs land here)' : ''}
- Stack: ${stackLine}          [detected]
- Verify before PR: ${verify}           [detected]
- Spec shape: knowledge/specs/TEMPLATE.md            [generated]

## Wiring the knowledge tools (rule 10)
Point any MCP-capable editor at specd. It serves this project's knowledge
base and its approved specs, and it is read-only — approval stays a
signed-in human in the app.

    { "mcpServers": { "specd": { "command": "specd", "args": ["mcp", "serve"] } } }

Needs the specd CLI on your PATH and \`specd login\` once per machine.
Tools: search_knowledge · get_doc · verify_citation · knowledge_health ·
spec_status · spec_pull · list_specs
`;
}

/**
 * What specd adds to a repository that already has working agreements.
 *
 * The full `renderAgentsMd` document is a complete set of engineering rules —
 * read the docs first, cite what you relied on, update them in the same PR —
 * and a team that has written its own AGENTS.md has usually said most of that
 * already, in its own words. Appending the whole thing under theirs produced
 * two statements of the same practice, which is worse than either: an agent
 * follows whichever it reads first, and a reader cannot tell which is current.
 *
 * So when there is an existing file, specd contributes only what is *its*:
 * the four things its machinery actually enforces, and where the knowledge base
 * lives. Everything general is left to the team, because they already said it
 * and it is their repository.
 */
export function renderAgentsSupplement(input: {
  isPrimary: boolean;
  projectName: string;
}): string {
  const { isPrimary, projectName } = input;
  const asBuiltHome = isPrimary ? 'this repo' : `the primary repo of ${projectName}`;

  return `## specd — added by setup

This repository is spec-driven with [specd](https://github.com/unitypark/specd).
**The agreements above still stand.** What follows is only the part specd's own
machinery depends on — where the two overlap, yours win and this block is the
one to correct.

1. **Work arrives as an approved spec.** Fetch it with \`specd spec pull <id>\`.
   The server refuses to serve a spec no human has approved, so this is not a
   convention you can route around.
2. **Branch \`spec/<ID>-<slug>\`, and title the pull request \`[<ID>] - <Title>\`.**
   The merge webhook matches that shape back to the spec; a branch named
   anything else is delivered work specd cannot record.
3. **The last task of a spec files its as-built copy** to
   \`knowledge/specs/<ID>-<slug>.md\` in ${asBuiltHome}. That record is what
   grounds the next spec.
4. **The knowledge base is \`knowledge/\`**, and it is what specs get drafted
   and cited from. Start at [knowledge/README.md](knowledge/README.md); specd
   re-indexes the directory whenever a change to it merges.

## Wiring the knowledge tools

Point any MCP-capable editor at specd. It serves this project's knowledge base
and its approved specs, read-only — approval stays a signed-in human in the app.

    { "mcpServers": { "specd": { "command": "specd", "args": ["mcp", "serve"] } } }

Needs the specd CLI on your PATH and \`specd login\` once per machine.
Tools: search_knowledge · get_doc · verify_citation · knowledge_health ·
spec_status · spec_pull · list_specs
`;
}

export function renderClaudeMd(): string {
  return `# CLAUDE.md

@AGENTS.md

<!--
  specd emits both files by design (D6): AGENTS.md is canonical and read by
  most agents; this file is a thin pointer so Claude Code picks up the same
  rules natively. Edit AGENTS.md — this file needs no maintenance.
-->
`;
}

/**
 * The fence around specd's contribution to a file it did not write.
 *
 * Onboarding a repository that already has agent instructions is not a licence
 * to replace them: they are a team's accumulated rules, and a scan that has
 * read the repo for ten minutes is in no position to overrule them. So the
 * generated agreements are *appended* inside these markers, which give the
 * merge two properties it needs — a human can see at a glance which half specd
 * wrote, and a re-grounding run can update that half in place instead of
 * stacking a second copy underneath the first.
 */
export const SPECD_BLOCK_BEGIN =
  '<!-- specd:begin — generated by specd. Re-running setup replaces everything between these markers; your own text above is never touched. -->';
export const SPECD_BLOCK_END = '<!-- specd:end -->';

/** The H1 specd's own AGENTS.md always opens with. */
const GENERATED_HEADING = '# Working agreements for AI agents (generated by specd';

/**
 * Fold specd's working agreements into whatever agent instructions the repo
 * already has.
 *
 * Three cases, in the order they are checked:
 *
 *   1. specd's markers are already in the file — a previous setup PR was
 *      merged. Replace what is between them and leave the rest alone.
 *   2. The file is specd's own output from before markers existed. Replacing
 *      it wholesale is the right move: nobody's writing is being discarded.
 *   3. Anything else is a team's own file. It survives verbatim, and the
 *      generated rules land underneath it, fenced and labelled.
 */
export function mergeAgentsMd(
  existing: string | null | undefined,
  generated: string,
  /**
   * What to append when the repository already has agreements. Falls back to
   * the whole document, which is what this used to do unconditionally and is
   * still right when there is nothing to duplicate.
   */
  supplement?: string,
): string {
  const current = (existing ?? '').trim();
  if (!current) return generated;

  // The markers are HTML comments, which every markdown renderer hides — so on
  // the pull request page the fence is invisible and specd's rules would read
  // as the team's own. The heading and the sentence under it are what a human
  // actually sees, and they are the half that says which rules are whose.
  const block =
    `${SPECD_BLOCK_BEGIN}\n\n` +
    `${stripHeading(supplement ?? generated)}\n${SPECD_BLOCK_END}\n`;

  const replaced = replaceFencedBlock(current, block);
  if (replaced) return replaced;

  if (current.startsWith(GENERATED_HEADING)) return generated;

  return `${current}\n\n---\n\n${block}`;
}

/**
 * The Claude Code pointer, reconciled with one the repo may already have.
 *
 * Returns `null` when there is nothing to do — an existing CLAUDE.md that
 * already imports AGENTS.md is already correct, and rewriting it would put a
 * no-op file in the setup PR for a reviewer to wonder about.
 */
export function mergeClaudeMd(existing: string | null | undefined): string | null {
  const current = (existing ?? '').trim();
  if (!current) return renderClaudeMd();
  if (/^\s*@AGENTS\.md\s*$/m.test(current)) return null;

  // The import has to be a line of its own for Claude Code to follow it, and
  // it goes first: the file's own content then reads as additions to the
  // agreements rather than as a competing set of rules.
  return `@AGENTS.md\n\n${current}\n`;
}

/** Drops the leading H1 — the merged file already has one. */
function stripHeading(markdown: string): string {
  return markdown.replace(/^#\s.*\n+/, '').trim();
}

/** Swap a previously written specd block for a new one, or report there is none. */
function replaceFencedBlock(current: string, block: string): string | null {
  const start = current.indexOf(SPECD_BLOCK_BEGIN);
  if (start === -1) return null;

  const endMarker = current.indexOf(SPECD_BLOCK_END, start);
  // An opened fence with no close means someone edited across it. Appending a
  // second block would be worse than leaving the damaged one alone, so the
  // whole tail from the marker is replaced.
  const end = endMarker === -1 ? current.length : endMarker + SPECD_BLOCK_END.length;

  return `${current.slice(0, start)}${block}${current.slice(end).trimStart()}`.trimEnd() + '\n';
}
