import { type DetectedStack, describeStack } from './stack.js';

/**
 * The knowledge/ scaffold. Every generated doc carries a DRAFT banner and
 * per-claim UNVERIFIED markers — the wizard must not lie (§6). Credibility
 * with senior engineers is won or lost in these files.
 */

export const DRAFT_BANNER = `> **status: DRAFT — review before trusting.** Generated by specd from a
> read-only repo scan. Claims the agent could not ground in the code are
> marked \`UNVERIFIED\`. Merging this PR is how you adopt it; edit freely.`;

export interface ScaffoldFile {
  path: string;
  content: string;
}

export function renderKnowledgeReadme(input: {
  repoName: string;
  stack: DetectedStack;
  projectName: string;
}): string {
  return `# knowledge/ — start here

${DRAFT_BANNER}

This directory is the curated context for **${input.repoName}** (project:
${input.projectName}). Agents read it before writing code; humans read it before
reviewing. It is the source of truth — specd only holds a derived index.

## Reading order

| Read this | When |
| --- | --- |
| \`architecture.md\` | Before any change that crosses a module boundary |
| \`conventions.md\` | Before writing code — lint rules, layout, test patterns |
| \`glossary.md\` | When a domain term is unfamiliar |
| \`decisions/\` | Before revisiting a choice someone already made |
| \`runbooks/\` | When running, deploying or debugging locally |
| \`specs/\` | Before designing something adjacent — every delivered spec lands here |

## How this stays alive

- Docs ride the change: update them in the **same PR** as the code (AGENTS.md rule 3).
- Delivered specs are appended to \`specs/\` automatically as the last task of every spec.
- specd re-indexes on merge and flags docs that have drifted from the code.

Stack: ${describeStack(input.stack) || '_not detected — please fill in_'}
`;
}

export function renderArchitecture(input: {
  repoName: string;
  stack: DetectedStack;
  topLevelDirs: string[];
  entryPoints: string[];
}): string {
  const { repoName, stack, topLevelDirs, entryPoints } = input;
  const dirRows = topLevelDirs.length
    ? topLevelDirs.map((d) => `| \`${d}/\` | UNVERIFIED — describe what lives here |`).join('\n')
    : '| _(no directories detected)_ | |';

  return `# Architecture — ${repoName}

${DRAFT_BANNER}

## Shape

- **Stack:** ${describeStack(stack) || '_not detected_'}  [detected]
- **Entry points:** ${entryPoints.length ? entryPoints.map((e) => `\`${e}\``).join(', ') : '_UNVERIFIED — none detected_'}

## Layout

| Path | Responsibility |
| --- | --- |
${dirRows}

## Boundaries

UNVERIFIED — the repo scan can see the file tree but not the intent behind it.
Describe here: which modules may call which, where transactions begin and end,
and what crosses a network boundary. This is the section agents lean on most.

## Data

UNVERIFIED — name the stores, what owns each table/collection, and the
migration story.

## Integrations

UNVERIFIED — external services this repo calls, and what happens when they fail.
`;
}

export function renderConventions(input: { repoName: string; stack: DetectedStack }): string {
  const { stack } = input;
  return `# Conventions — ${input.repoName}

${DRAFT_BANNER}

## Verify before opening a PR

\`\`\`
${stack.verifyCommand ?? '# UNVERIFIED — no verify command detected; add yours here'}
\`\`\`

## Detected

| Thing | Value |
| --- | --- |
| Language | ${stack.language} |
| Framework | ${stack.framework ?? '_none detected_'} |
| Package manager | ${stack.packageManager ?? '_none detected_'} |
| Test runner | ${stack.testRunner ?? '_none detected_'} |
| Linter | ${stack.linter ?? '_none detected_'} |

## Code style

UNVERIFIED — the scan reads config files, not taste. Record the decisions a
reviewer would otherwise repeat in every review: naming, file layout, error
handling, when to add an abstraction.

## Tests

UNVERIFIED — what must have a test, what may not, and how to run a subset.

## Git

UNVERIFIED — branch naming, commit style, review expectations. Note that specd
requires \`spec/<id>-<slug>\` branches for spec-driven work (AGENTS.md rule 6).
`;
}

export function renderGlossary(input: { repoName: string; terms: string[] }): string {
  const rows = input.terms.length
    ? input.terms.map((t) => `| **${t}** | UNVERIFIED — define in one sentence |`).join('\n')
    : '| _(no terms mined)_ | |';

  return `# Glossary — ${input.repoName}

${DRAFT_BANNER}

Domain terms mined from code and docs. The agent can spot the words; only a
human can say what they mean. Filling this in is the highest-leverage hour you
will spend on this directory.

| Term | Meaning |
| --- | --- |
${rows}
`;
}

export function renderAdoptionAdr(input: { projectName: string; date: string }): string {
  return `# 0001 — Adopt spec-driven delivery

- **Status:** accepted
- **Date:** ${input.date}
- **Project:** ${input.projectName}

## Context

AI coding agents produce inconsistent results when every session rediscovers the
codebase from raw source. Context evaporates when a session ends, conventions get
reinvented, and assumptions ship silently.

## Decision

Work reaches coding agents as a **human-approved spec**, never as a bare prompt.
Agents read \`knowledge/\` first, cite what they relied on, and file the as-built
spec back into \`knowledge/specs/\` in the same PR as the code.

The approval gate is structural: no agent may approve its own input.

## Consequences

- Every change is traceable to an approved spec and a named approver.
- \`knowledge/\` must be maintained in the same PR as the code it describes,
  or it rots and the next spec is grounded in fiction.
- Prompt injection via ticket text cannot reach a code-writing agent without
  surviving human review first.
`;
}

export function renderLocalDevRunbook(input: {
  repoName: string;
  stack: DetectedStack;
}): string {
  return `# Runbook — local development (${input.repoName})

${DRAFT_BANNER}

> **This is a generated stub.** Assign it an owner and fill it in — a runbook
> nobody has run is worse than no runbook.

## Prerequisites

UNVERIFIED — runtime versions, services, credentials.

## Run it

\`\`\`
${input.stack.packageManager ? `${input.stack.packageManager} install` : '# UNVERIFIED'}
# UNVERIFIED — the command that actually starts this thing
\`\`\`

## Verify

\`\`\`
${input.stack.verifyCommand ?? '# UNVERIFIED'}
\`\`\`

## When it breaks

UNVERIFIED — the three failures newcomers actually hit.
`;
}

export function renderDeployRunbook(input: { repoName: string }): string {
  return `# Runbook — deploy (${input.repoName})

${DRAFT_BANNER}

> **This is a generated stub.** Assign it an owner.

## Environments

UNVERIFIED — what exists, who can deploy to each.

## Deploy

UNVERIFIED — the actual command or pipeline.

## Roll back

UNVERIFIED — the fastest safe path backwards. Write this one first.

## Observability

UNVERIFIED — where the logs, metrics and alerts live.
`;
}

export function renderSpecsReadme(): string {
  return `# knowledge/specs/ — as-built record

Every delivered spec lands here as the final task of its own implementation
(AGENTS.md rule 7). This directory is **append-only**: never rewrite a past
spec — if reality diverged from the approved design, append a \`## Deviations\`
section to the existing file.

This is the loop that makes context compound. The next spec retrieves these.
`;
}

/** The complete setup-PR payload for one repo. */
export function renderScaffold(input: {
  repoName: string;
  projectName: string;
  isPrimary: boolean;
  stack: DetectedStack;
  topLevelDirs: string[];
  entryPoints: string[];
  glossaryTerms: string[];
  date: string;
  agentsMd: string;
  architectureMd?: string;
  conventionsMd?: string;
  glossaryMd?: string;
}): ScaffoldFile[] {
  return [
    { path: 'AGENTS.md', content: input.agentsMd },
    { path: 'CLAUDE.md', content: renderClaudeMdRef() },
    {
      path: 'knowledge/README.md',
      content: renderKnowledgeReadme({
        repoName: input.repoName,
        stack: input.stack,
        projectName: input.projectName,
      }),
    },
    {
      path: 'knowledge/architecture.md',
      content:
        input.architectureMd ??
        renderArchitecture({
          repoName: input.repoName,
          stack: input.stack,
          topLevelDirs: input.topLevelDirs,
          entryPoints: input.entryPoints,
        }),
    },
    {
      path: 'knowledge/conventions.md',
      content:
        input.conventionsMd ??
        renderConventions({ repoName: input.repoName, stack: input.stack }),
    },
    {
      path: 'knowledge/glossary.md',
      content:
        input.glossaryMd ??
        renderGlossary({ repoName: input.repoName, terms: input.glossaryTerms }),
    },
    {
      path: 'knowledge/decisions/0001-adopt-spec-driven.md',
      content: renderAdoptionAdr({ projectName: input.projectName, date: input.date }),
    },
    {
      path: 'knowledge/runbooks/local-dev.md',
      content: renderLocalDevRunbook({ repoName: input.repoName, stack: input.stack }),
    },
    { path: 'knowledge/runbooks/deploy.md', content: renderDeployRunbook({ repoName: input.repoName }) },
    { path: 'knowledge/specs/README.md', content: renderSpecsReadme() },
  ];
}

function renderClaudeMdRef(): string {
  return `# CLAUDE.md

@AGENTS.md

<!--
  specd emits both files by design (D6): AGENTS.md is canonical and read by
  most agents; this file is a thin pointer so Claude Code picks up the same
  rules natively. Edit AGENTS.md — this file needs no maintenance.
-->
`;
}

/** The setup PR description. It says exactly what the drafts are worth (§6). */
export function renderSetupPrBody(input: {
  repoName: string;
  projectName: string;
  fileCount: number;
  unverifiedCount: number;
  stackLine: string;
}): string {
  return `## specd setup — review me, then merge to adopt

This PR installs the working agreements and knowledge base for **${input.projectName}**.

**${input.fileCount} files**, all marked \`DRAFT\`. Detected stack: ${input.stackLine}.

### What is in here

- \`AGENTS.md\` — working agreements for AI agents (knowledge-first, spec-driven,
  as-built specs). \`CLAUDE.md\` imports it so Claude Code picks up the same rules.
- \`knowledge/\` — the curated wiki agents must read before implementing anything.

### Read this before you merge

These docs were drafted from a **read-only repo scan**. The scan can see your
file tree, manifests and config; it cannot see your intent. Every claim it
could not ground is marked **UNVERIFIED** — there are **${input.unverifiedCount}** of them.

**Do not treat generated text as verified.** Review it the way you would review
a new hire's first architecture write-up: the shape is useful, the details need
your judgement. Merging is adopting.

### After merging

1. Fill in the \`UNVERIFIED\` markers — the glossary and architecture boundaries
   pay for themselves fastest.
2. Write or import your first ticket.
3. Generate your first spec, review it, and stamp it.

_Opened by specd · git stays the source of truth for knowledge; the platform
only holds a derived index._
`;
}
