import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { LandingNav } from '@/components/LandingNav';
import { GALLERY, galleryEntry, galleryPack } from '@/lib/gallery';
import styles from '../../landing.module.css';
import gallery from '../gallery.module.css';

/**
 * One stack, one page — the SEO surface §3 asks for.
 *
 * Everything rendered below comes from `galleryPack`, which runs the
 * product's own `detectStack` and templates. If specd's output changes, this
 * page changes with it; there is no second copy to forget to update.
 */

export function generateStaticParams() {
  return GALLERY.map((entry) => ({ slug: entry.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const entry = galleryEntry(slug);
  if (!entry) return { title: 'specd — templates' };

  const { summary } = galleryPack(entry);
  return {
    title: `${entry.title} AGENTS.md + knowledge/ scaffold — specd`,
    description: `The AGENTS.md working agreements and knowledge/ scaffold specd generates for a ${entry.title} repository (${summary}). Generated by the product, not written for the page.`,
  };
}

export default async function TemplatePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const entry = galleryEntry(slug);
  if (!entry) notFound();

  const { stack, summary, agentsMd, files } = galleryPack(entry);
  const knowledge = files.filter((f) => f.path.startsWith('knowledge/'));

  return (
    <main className={styles.page}>
      <LandingNav />
      <section className={styles.subhead}>
        <div className={styles.subin}>
          <Link href="/templates" className={styles.back}>
            ← ALL TEMPLATES
          </Link>
          <span className="tag">{entry.title.toUpperCase()}</span>
          <h1 className={styles.subh1}>{entry.title} — what specd generates</h1>
          <p className={styles.lede}>{entry.blurb}</p>

          <span className="tag">DETECTED FROM THE REPOSITORY</span>
          <div className={gallery.facts}>
            <div>
              <dt>Stack</dt>
              <dd>{summary}</dd>
            </div>
            <div>
              <dt>Verify command</dt>
              <dd>
                <code>{stack.verifyCommand}</code>
              </dd>
            </div>
          </div>
          <p className={gallery.note}>
            specd runs that command itself after a build — the agent is given editing tools and
            never a shell, so nothing a model emits becomes a command. If it cannot run, the build
            says so rather than reporting a pass.
          </p>

          <span className="tag">AGENTS.md</span>
          <p className={styles.lede}>
            The working agreements, installed as a pull request. <code>CLAUDE.md</code> ships
            beside it as a one-line import, so editing either keeps both in sync.
          </p>
          <pre className={gallery.code}>
            <code>{agentsMd}</code>
          </pre>

          <span className="tag">knowledge/</span>
          <p className={styles.lede}>
            The base every agent reads before it writes. Drafted from a read-only scan, marked as
            a draft, and yours to correct — git stays the only source of truth.
          </p>
          <div className={gallery.tree}>
            {knowledge.map((file) => (
              <div key={file.path} className={gallery.treeRow}>
                <code>{file.path}</code>
                <span>{firstLine(file.content)}</span>
              </div>
            ))}
          </div>

          <span className="tag">THE LOOP THIS STARTS</span>
          <p className={styles.lede}>
            Merging the pull request is how you adopt it. From then on every ticket becomes a spec
            grounded in these documents, a person approves it, an agent implements it, and the
            as-built spec is filed back into <code>knowledge/specs/</code> — so the next spec is
            written against everything the last one learned.
          </p>

          <div className={gallery.cta}>
            <Link href="/setup" className={gallery.ctaBtn}>
              Set this up on your repo →
            </Link>
            <Link href="/docs" className={gallery.ctaAlt}>
              Read the docs
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}

/** The first meaningful line of a generated doc, as a one-line description. */
function firstLine(content: string): string {
  const line = content
    .split('\n')
    .map((l) => l.replace(/^#+\s*/, '').trim())
    .find((l) => l.length > 0);
  return line ? line.slice(0, 110) : '';
}
